# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

#PS1="\[\033[0;37;40m\u\033[0;33;40m@\033[0;32;40m\h:\033[0;33;40m\W$ \033[0m]"
# 31 red
# 32 green
# 33 yellow
sc="\[\033[0;33;60m\]"
hn="\[\033[0;32;60m\]"
un="\[\033[0;31;60m\]"
wc="\[\033[0m\]"

PS1=${un}'\u'${sc}@${hn}'\h':${sc}'~$ '${wc}

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"'
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    #alias dir='ls --color=auto --format=vertical'
    #alias vdir='ls --color=auto --format=long'
fi

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# My alias'
alias temperature="cat /proc/acpi/thermal_zone/THRM/temperature"
alias php-on="sudo service apache start; sudo service mysql_server start"
alias php-off="sudo service apache stop; sudo service mysql_server stop"
alias nocaps="setxkbmap -option ctrl:nocaps"
alias caps="setxkbmap -option -option capslock:caps"
# ssh alias
# kelebek scp
#alias lastfm-log="tail -f /var/log/lastfm/lastfm.log | ccze -A"

# My variable
export EDITOR="emacs -nw"
# pisi packagekit backend
export GIT_AUTHOR_NAME='Aşkın Yollu'
export GIT_AUTHOR_EMAIL=askin@askin.ws
export GIT_COMMITTER_NAME='Aşkın Yollu'
export GIT_COMMITTER_EMAIL=askin@askin.ws

# my java classpath
export CLASSPATH=.:~/java-files/cem12x.jar:~/java-files/mysql-connector-java-5.1.6-bin.jar
