#!/bin/bash
# Makinaya erişilebilinceye kadar ping atar
# Ping attıktan sonra uyarı gösterir
# Her 10 ping isleminden sonra hata uyarısı verir

if [ $# -lt 1 ]; then
    echo "Eksik parametre"
    exit 1
fi

IP=$1

# Kesmeyi algila
trap bashtrap INT
bashtrap() {
    notify-send "Kesme geldi" "IP: $IP" -i error
    exit 1
}

counter=0
while [ 1 ]; do
    if ping -c 1 $1; then
        notify-send "Ping Başarılı" "IP: $IP" -i emblem-OK
	mpg123 /home/home/bin/ping-notify-music.mp3
	mpg123 /home/home/bin/ping-notify-music.mp3
        break
    else
        counter=$((counter + 1))
        if [ $counter == 10 ]; then
            notify-send "Ping Başarısız" "IP: $IP" -i dialog-warning
            counter=0
        fi
    fi
done
